"""
Local CoCa ViT-L-14 text encoder using ONNX Runtime.

Provides text-to-embedding inference without torch/open_clip dependencies.
Only requires: onnxruntime, regex, numpy.

The ONNX model and BPE vocab are generated by:
    uv run scripts/export_coca_text_encoder_onnx.py --quantize

The BPE vocab (bpe_simple_vocab_16e6.txt.gz) must sit next to the ONNX model.
Configure via COCA_TEXT_ENCODER_MODEL_PATH env var.

Usage:
    from backend.dataroom.utils.coca_text_encoder import encode_text

    embedding = encode_text("shoes")  # list[float], 768-dim, L2-normalized
"""

import gzip
import logging
import os
from functools import lru_cache
from threading import Lock

import numpy as np
import regex as re

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# BPE Tokenizer (extracted from open_clip SimpleTokenizer, torch-free)
# ---------------------------------------------------------------------------

_CONTEXT_LENGTH = 76  # CoCa ViT-L-14 context length
_SOT_TOKEN = 49406  # <start_of_text>
_EOT_TOKEN = 49407  # <end_of_text>


@lru_cache
def _bytes_to_unicode():
    bs = list(range(ord("!"), ord("~") + 1)) + list(range(ord("¡"), ord("¬") + 1)) + list(range(ord("®"), ord("ÿ") + 1))
    cs = bs[:]
    n = 0
    for b in range(2**8):
        if b not in bs:
            bs.append(b)
            cs.append(2**8 + n)
            n += 1
    return dict(zip(bs, [chr(n) for n in cs], strict=False))


def _get_pairs(word):
    pairs = set()
    prev = word[0]
    for char in word[1:]:
        pairs.add((prev, char))
        prev = char
    return pairs


class _BPETokenizer:
    """Minimal CLIP BPE tokenizer — no torch dependency."""

    def __init__(self, bpe_path: str, context_length: int = _CONTEXT_LENGTH):
        self.byte_encoder = _bytes_to_unicode()
        self.context_length = context_length

        merges = gzip.open(bpe_path).read().decode("utf-8").split("\n")
        merges = merges[1 : 49152 - 256 - 2 + 1]
        merges = [tuple(m.split()) for m in merges]

        vocab = list(self.byte_encoder.values())
        vocab = vocab + [v + "</w>" for v in vocab]
        for merge in merges:
            vocab.append("".join(merge))
        vocab.extend(["<start_of_text>", "<end_of_text>"])

        self.encoder = dict(zip(vocab, range(len(vocab)), strict=False))
        self.bpe_ranks = dict(zip(merges, range(len(merges)), strict=False))
        self.cache: dict[str, str] = {}
        self.pat = re.compile(
            r"""<start_of_text>|<end_of_text>|'s|'t|'re|'ve|'m|'ll|'d""" r"""|[\p{L}]+|[\p{N}]|[^\s\p{L}\p{N}]+""",
            re.IGNORECASE,
        )

    def _bpe(self, token: str) -> str:
        if token in self.cache:
            return self.cache[token]
        word = (*tuple(token[:-1]), token[-1] + "</w>")
        pairs = _get_pairs(word)
        if not pairs:
            return token + "</w>"
        while True:
            bigram = min(pairs, key=lambda p: self.bpe_ranks.get(p, float("inf")))
            if bigram not in self.bpe_ranks:
                break
            first, second = bigram
            new_word = []
            i = 0
            while i < len(word):
                try:
                    j = word.index(first, i)
                except ValueError:
                    new_word.extend(word[i:])
                    break
                new_word.extend(word[i:j])
                if word[j] == first and j < len(word) - 1 and word[j + 1] == second:
                    new_word.append(first + second)
                    i = j + 2
                else:
                    new_word.append(word[j])
                    i = j + 1
            word = tuple(new_word)
            if len(word) == 1:
                break
            pairs = _get_pairs(word)
        result = " ".join(word)
        self.cache[token] = result
        return result

    def tokenize(self, texts: list[str]) -> np.ndarray:
        """Tokenize a list of strings into padded int64 arrays.

        Returns shape [len(texts), context_length].
        """
        all_tokens = []
        for text in texts:
            text = text.lower()
            tokens = [_SOT_TOKEN]
            for match in re.findall(self.pat, text):
                encoded = "".join(self.byte_encoder[b] for b in match.encode("utf-8"))
                tokens.extend(self.encoder[bt] for bt in self._bpe(encoded).split(" "))
            tokens.append(_EOT_TOKEN)
            if len(tokens) > self.context_length:
                tokens = tokens[: self.context_length]
                tokens[-1] = _EOT_TOKEN
            all_tokens.append(tokens)

        result = np.zeros((len(texts), self.context_length), dtype=np.int64)
        for i, tokens in enumerate(all_tokens):
            result[i, : len(tokens)] = tokens
        return result


# ---------------------------------------------------------------------------
# ONNX Inference
# ---------------------------------------------------------------------------

_lock = Lock()
_encoder_instance = None


class CoCaTextEncoder:
    """ONNX-based CoCa text encoder. Thread-safe, lazily loaded."""

    def __init__(self, model_path: str):
        import onnxruntime as ort

        model_dir = os.path.dirname(model_path)
        bpe_path = os.path.join(model_dir, "bpe_simple_vocab_16e6.txt.gz")
        self.tokenizer = _BPETokenizer(bpe_path)
        self.session = ort.InferenceSession(
            model_path,
            providers=["CPUExecutionProvider"],
        )
        logger.info("CoCa text encoder loaded from %s", model_path)

    def encode(self, text: str) -> list[float]:
        """Encode a single text string into a 768-dim L2-normalized embedding."""
        tokens = self.tokenizer.tokenize([text])
        embedding = self.session.run(None, {"input_ids": tokens})[0]
        return embedding[0].tolist()

    def encode_batch(self, texts: list[str]) -> list[list[float]]:
        """Encode multiple texts at once."""
        tokens = self.tokenizer.tokenize(texts)
        embeddings = self.session.run(None, {"input_ids": tokens})[0]
        return embeddings.tolist()


def _get_encoder() -> CoCaTextEncoder | None:
    """Get or create the singleton encoder instance."""
    global _encoder_instance
    if _encoder_instance is not None:
        return _encoder_instance

    from django.conf import settings

    model_path = getattr(settings, "COCA_TEXT_ENCODER_MODEL_PATH", None)
    if not model_path:
        return None

    with _lock:
        if _encoder_instance is None:
            _encoder_instance = CoCaTextEncoder(model_path)
    return _encoder_instance


def encode_text(text: str) -> list[float] | None:
    """Encode text using the local ONNX model. Returns None if not configured."""
    encoder = _get_encoder()
    if encoder is None:
        return None
    return encoder.encode(text)
