# Generated by Django 5.1.6 on 2025-04-07 08:22

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                message='Can only contain alphanumeric characters, dashes, and underscores',
                                regex='^[a-zA-Z0-9_-]+$',
                            ),
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('string', 'String'),
                            ('number', 'Number'),
                            ('integer', 'Integer'),
                            ('array', 'Array'),
                            ('boolean', 'Boolean'),
                            ('null', 'Null'),
                        ],
                        default='string',
                        max_length=20,
                    ),
                ),
                (
                    'string_format',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('date-time', 'Date-time'),
                            ('time', 'Time'),
                            ('date', 'Date'),
                            ('duration', 'Duration'),
                            ('email', 'Email'),
                            ('hostname', 'Hostname'),
                            ('ipv4', 'IPv4'),
                            ('ipv6', 'IPv6'),
                            ('uuid', 'UUID'),
                            ('uri', 'URI'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'array_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('string', 'String'),
                            ('number', 'Number'),
                            ('integer', 'Integer'),
                            ('array', 'Array'),
                            ('boolean', 'Boolean'),
                            ('null', 'Null'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('enum_choices', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Is validation for this field enabled?')),
                (
                    'is_mapped',
                    models.BooleanField(
                        default=False, editable=False, help_text='Is this field present in OpenSearch mapping?'
                    ),
                ),
                ('image_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LatentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        max_length=128,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                message='Can only contain alphanumeric characters, dashes, and underscores',
                                regex='^[a-zA-Z0-9_-]+$',
                            ),
                        ],
                    ),
                ),
                ('is_mask', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                (
                    'is_mapped',
                    models.BooleanField(
                        default=False, editable=False, help_text='Is this field present in OpenSearch mapping?'
                    ),
                ),
                ('image_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        max_length=300,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                message='Can only contain alphanumeric characters, dashes, and underscores',
                                regex='^[a-zA-Z0-9_-]+$',
                            ),
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True, default='')),
                ('image_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'stats_type',
                    models.CharField(
                        choices=[
                            ('total_images', 'Total images'),
                            ('total_datasets', 'Total datasets'),
                            ('image_sources', 'Image sources'),
                            ('image_aspect_ratio_fractions', 'Image aspect ratio fractions'),
                            ('images_missing_thumbnail', 'Images missing thumbnail'),
                            ('images_missing_coca_embedding', 'Images missing COCA embedding'),
                            ('images_missing_tags', 'Images missing tags'),
                            ('images_missing_duplicate_state', 'Images missing duplicate state'),
                            ('images_marked_as_duplicates', 'Images marked as duplicates'),
                            ('images_marked_for_deletion', 'Images marked for deletion'),
                            ('images_with_disabled_latents', 'Images with disabled latents'),
                        ],
                        max_length=40,
                    ),
                ),
                ('group_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('prev_value', models.PositiveIntegerField(default=0)),
                ('prev_date_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stats',
                'unique_together': {('stats_type', 'group_name')},
            },
        ),
    ]
