# Generated by Django 5.1.6 on 2025-05-14 18:06

import backend.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0001_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesfield',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    backend.common.validators.AlphanumericValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='latenttype',
            name='name',
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    backend.common.validators.AlphanumericValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                max_length=300,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    backend.common.validators.AlphanumericValidator(),
                ],
            ),
        ),
    ]
