# Generated by Django 5.1.6 on 2025-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0003_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesfield',
            name='is_indexed',
            field=models.BooleanField(default=True, help_text='Whether this attribute should be indexed for search. Non-indexed attributes are stored but not searchable.'),
        ),
    ]
