# Generated by Django 5.1.6 on 2025-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0004_add_is_indexed_field_to_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesfield',
            name='array_type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('number', 'Number'), ('integer', 'Integer'), ('object', 'Object'), ('array', 'Array'), ('boolean', 'Boolean'), ('null', 'Null')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attributesfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('integer', 'Integer'), ('object', 'Object'), ('array', 'Array'), ('boolean', 'Boolean'), ('null', 'Null')], default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributesfield',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this attribute should be indexed for search. Non-indexed attributes are stored but not searchable.'),
        ),
    ]
