# Generated by Django 5.1.6 on 2026-04-28 13:44

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataroom', '0006_add_cover_image_id_to_dataset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'name',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='name must be lowercase alphanumeric with underscores',
                                regex='^[a-z0-9_]+$',
                            )
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                (
                    'name',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='name must be lowercase alphanumeric with underscores',
                                regex='^[a-z0-9_]+$',
                            )
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True, default='')),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupTypeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False)),
                (
                    'group_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='type_roles',
                        to='dataroom.grouptype',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='type_roles',
                        to='dataroom.role',
                    ),
                ),
            ],
            options={
                'ordering': ('group_type', 'role'),
            },
        ),
        migrations.AddConstraint(
            model_name='grouptyperole',
            constraint=models.UniqueConstraint(fields=('group_type', 'role'), name='grouptyperole_uniq'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='image_groups',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='groups',
                        to='dataroom.grouptype',
                    ),
                ),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='grouptype',
            name='roles',
            field=models.ManyToManyField(
                related_name='group_types',
                through='dataroom.GroupTypeRole',
                to='dataroom.role',
            ),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['type'], name='dataroom_gr_type_id_e02647_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=('name',),
                name='dataroom_group_name_unique_when_active',
            ),
        ),
    ]
