# Generated by Django 5.1.6 on 2026-04-28 13:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataroom', '0007_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='dataroom.group',
                    ),
                ),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['image_id'], name='dataroom_me_image_i_24608c_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['group', 'role'], name='dataroom_me_group_i_bc05cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'image_id'), name='memberships_group_image_uniq'),
        ),
    ]
