# Generated by Django 5.1.6 on 2026-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0008_membership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='memberships_group_image_uniq',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'image_id', 'role'), name='memberships_group_image_role_uniq'),
        ),
    ]
