# Generated by Django 5.1.6 on 2026-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0009_membership_multi_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='os_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['os_synced'], name='dataroom_me_os_sync_a38665_idx'),
        ),
    ]
