# Generated by Django 5.1.6 on 2026-05-26.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0010_membership_deleted_at_membership_os_synced_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membership',
            name='dataroom_me_os_sync_a38665_idx',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='os_synced',
        ),
    ]
