# Generated by Django 5.1.6 on 2026-05-27 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0011_remove_membership_os_synced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-date_created'], name='dataroom_gr_date_cr_6d4c06_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['group', 'deleted_at'], name='dataroom_me_group_i_66fc4f_idx'),
        ),
    ]
