# Generated by Django 5.1.6 on 2026-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0012_group_date_created_membership_group_deleted_at_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='os_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(condition=models.Q(('os_synced', False)), fields=['group'], name='memberships_unsynced_idx'),
        ),
    ]
