# Generated by Django 5.1.6 on 2026-05-30 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumbered 0014 -> 0015 and re-pointed onto 0014_query to resolve the
    # multiple-leaf-node collision: main shipped 0014_query off the same parent
    # (0013_membership_os_synced) as this migration, so both can't be 0014.
    dependencies = [
        ('dataroom', '0014_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('slug_version', models.CharField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_frozen', models.BooleanField(default=False)),
                ('cover_image_id', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typed_datasets', to='dataroom.grouptype')),
            ],
            options={
                'ordering': ('slug', '-version'),
            },
        ),
        migrations.CreateModel(
            name='TypedDatasetMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dataroom.typeddataset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_dataset_memberships', to='dataroom.group')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddConstraint(
            model_name='typeddataset',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='typed_dataset_slug_version_idx'),
        ),
        migrations.AddIndex(
            model_name='typeddatasetmembership',
            index=models.Index(fields=['dataset', 'deleted_at'], name='dataroom_ty_dataset_f7df87_idx'),
        ),
        migrations.AddConstraint(
            model_name='typeddatasetmembership',
            constraint=models.UniqueConstraint(fields=('dataset', 'group'), name='typed_dataset_membership_uniq'),
        ),
    ]
