# Generated by Django 5.1.6 on 2026-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    # Follows the renumbered 0015 (was 0014_typeddataset...), bumped to 0016 to
    # stay after main's 0014_query — see the note in 0015 for the collision.
    dependencies = [
        ('dataroom', '0015_typeddataset_typeddatasetmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeddatasetmembership',
            name='os_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='typeddatasetmembership',
            index=models.Index(condition=models.Q(('os_synced', False)), fields=['dataset'], name='typed_dataset_unsynced_idx'),
        ),
    ]
