# Generated by Django 5.1.6 on 2026-09-08 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# The classifier service stores a backbone's features as the latent
# <backbone>_<image_size>_features.
BACKBONES = ('vits14', 'vitb14', 'vitl14', 'vitg14', 'vits14_reg', 'vitb14_reg', 'vitl14_reg', 'vitg14_reg')
IMAGE_SIZE = 518


def create_latent_types(apps, schema_editor):
    LatentType = apps.get_model('dataroom', 'LatentType')
    for backbone in BACKBONES:
        LatentType.objects.get_or_create(name=f'{backbone}_{IMAGE_SIZE}_features')


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0019_remove_dataset_typed_dataset_slug_version_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('slug_version', models.CharField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('version_note', models.TextField(blank=True, default='')),
                ('embedding_space', models.CharField(blank=True, default='', max_length=64)),
                ('is_frozen', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('extra_neg_datasets', models.ManyToManyField(blank=True, related_name='classifiers_extra_neg', to='dataroom.dataset')),
                ('extra_pos_datasets', models.ManyToManyField(blank=True, related_name='classifiers_extra_pos', to='dataroom.dataset')),
                ('main_neg_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifier_main_neg', to='dataroom.dataset')),
                ('main_pos_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifier_main_pos', to='dataroom.dataset')),
                ('val_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classifier_val', to='dataroom.dataset')),
            ],
            options={
                'ordering': ('slug', '-version'),
            },
        ),
        migrations.CreateModel(
            name='ClassifierTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed')], default='training', max_length=16)),
                ('dagster_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=64)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('forced', models.BooleanField(default=False)),
                ('n_pos', models.PositiveIntegerField(default=0)),
                ('n_neg', models.PositiveIntegerField(default=0)),
                ('n_val', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='dataroom.classifier')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ClassifierApplyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('launched', 'Launched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='launched', max_length=16)),
                ('dagster_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_type', models.CharField(max_length=16)),
                ('target_value', models.CharField(blank=True, default='', max_length=255)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_runs', to='dataroom.classifier')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_runs', to='dataroom.classifiertraining')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddConstraint(
            model_name='classifier',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='classifier_slug_version_idx'),
        ),
        migrations.RunPython(create_latent_types, migrations.RunPython.noop),
    ]
