/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DataRoom API
 * Store training images at scale.
 * OpenAPI spec version: 1.0.0
 */
/**
 * * `add` - add
* `remove` - remove
 */
export enum ActionEnum {
  add= 'add',
  remove= 'remove',

}
// eslint-disable-next-line @typescript-eslint/no-redeclare
// @ts-ignore TS2450
export const AttributeFieldStringFormat = {...StringFormatEnum,...BlankEnum,...NullEnum,} as const
/**
 * @nullable
 */
export type AttributeFieldStringFormat = typeof AttributeFieldStringFormat[keyof typeof AttributeFieldStringFormat]  | null;

/**
 * @nullable
 */
export type AttributeFieldEnumChoices = {[key: string]: unknown} | null;

export interface AttributeField {
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  name: string;
  /** @maxLength 300 */
  description?: string;
  field_type?: FieldTypeEnum;
  /** @nullable */
  string_format?: AttributeFieldStringFormat;
  /** Is validation for this field enabled? */
  is_enabled?: boolean;
  /** Whether this attribute should be indexed for search. Non-indexed attributes are stored but not searchable. */
  is_indexed?: boolean;
  readonly image_count: number;
  /** @nullable */
  enum_choices?: AttributeFieldEnumChoices;
}

export enum BlankEnum {
  ''= '',

}
// eslint-disable-next-line @typescript-eslint/no-redeclare
// @ts-ignore TS2450
export const ClassifierEmbeddingSpace = {...EmbeddingSpaceEnum,...BlankEnum,} as const
export interface Classifier {
  readonly slug_version: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  readonly version: number;
  /** @maxLength 100 */
  name: string;
  description?: string;
  version_note?: string;
  readonly author: User;
  readonly main_pos_dataset: string;
  readonly main_neg_dataset: string;
  readonly val_dataset: string;
  extra_pos_datasets?: string[];
  extra_neg_datasets?: string[];
  readonly counts: ExampleCounts;
  readonly pos_count: number;
  readonly neg_count: number;
  embedding_space?: typeof ClassifierEmbeddingSpace[keyof typeof ClassifierEmbeddingSpace] ;
  is_frozen?: boolean;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * What to score, and with which trained model.
 */
export interface ClassifierApply {
  target_type: TargetTypeEnum;
  target_value?: string;
  /**
   * Which training's model to apply. Omit for the latest trained one.
   * @nullable
   */
  training_id?: string | null;
}

export interface ClassifierApplyRun {
  readonly id: string;
  readonly status: ClassifierApplyRunStatusEnum;
  readonly dagster_run_id: string;
  /** @nullable */
  readonly dagster_run_url: string | null;
  readonly training_id: string;
  readonly model_id: string;
  readonly target_type: string;
  readonly target_value: string;
  readonly processed: number;
  /** @nullable */
  readonly total: number | null;
  readonly error: string;
  readonly author: User;
  readonly date_created: string;
  readonly date_updated: string;
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
// @ts-ignore TS2450
export const ClassifierApplyRunReportStatus = {...ClassifierApplyRunReportStatusEnum,...NullEnum,} as const
/**
 * @nullable
 */
export type ClassifierApplyRunReportStatus = typeof ClassifierApplyRunReportStatus[keyof typeof ClassifierApplyRunReportStatus]  | null;

/**
 * Progress/terminal reports of an apply run.
 */
export interface ClassifierApplyRunReport {
  /** @nullable */
  status?: ClassifierApplyRunReportStatus;
  /**
   * @minimum 0
   * @nullable
   */
  total?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  processed?: number | null;
  error?: string;
}

/**
 * * `running` - running
* `completed` - completed
* `failed` - failed
 */
export enum ClassifierApplyRunReportStatusEnum {
  running= 'running',
  completed= 'completed',
  failed= 'failed',

}
/**
 * * `launched` - Launched
* `running` - Running
* `completed` - Completed
* `failed` - Failed
 */
export enum ClassifierApplyRunStatusEnum {
  launched= 'launched',
  running= 'running',
  completed= 'completed',
  failed= 'failed',

}
// eslint-disable-next-line @typescript-eslint/no-redeclare
// @ts-ignore TS2450
export const ClassifierCreateEmbeddingSpace = {...EmbeddingSpaceEnum,...BlankEnum,} as const
/**
 * Create: ``slug`` is writable, and must be a slug nothing else uses.

Reusing a slug used to make the next version, sharing the example datasets
with the version before it. That quietly broke locking: freezing one
version's datasets froze the other version's too, leaving it unlabellable.
New versions come from the ``new-version`` endpoint, which gives each one
its own copies.
 */
export interface ClassifierCreate {
  readonly slug_version: string;
  /**
   * @maxLength 100
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug: string;
  readonly version: number;
  /** @maxLength 100 */
  name: string;
  description?: string;
  version_note?: string;
  readonly author: User;
  readonly main_pos_dataset: string;
  readonly main_neg_dataset: string;
  readonly val_dataset: string;
  extra_pos_datasets?: string[];
  extra_neg_datasets?: string[];
  readonly counts: ExampleCounts;
  readonly pos_count: number;
  readonly neg_count: number;
  embedding_space?: typeof ClassifierCreateEmbeddingSpace[keyof typeof ClassifierCreateEmbeddingSpace] ;
  is_frozen?: boolean;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * Which examples to hold out of training.

``random`` re-draws the whole held-out set at the given fraction, sampling
each side separately: a validation set drawn from the pile as a whole can
come out nearly all negatives (they usually outnumber positives), and a
score measured on it would say almost nothing about the positives.

``manual`` edits the set an image at a time — the way to fix a draw that
put the wrong images in it, or to hold out a specific set by hand.

``preview`` samples without writing, so a caller can show the draw and let
someone adjust it before it counts. Committing the adjusted draw is then a
``manual`` call with ``replace``.
 */
export interface ClassifierHoldout {
  mode: ModeEnum;
  /**
   * ``random``: the share of EACH side to hold out.
   * @minimum 0.01
   * @maximum 0.9
   */
  fraction?: number;
  /**
   * ``random``: draw reproducibly. Omit for a fresh draw. The draw is stored as dataset membership either way, so it stays put once made.
   * @nullable
   */
  seed?: number | null;
  /** ``manual``: the images to hold out or put back. */
  image_ids?: string[];
  /** ``manual``: whether these images join the held-out set or leave it.

* `add` - add
* `remove` - remove */
  action?: ActionEnum;
  /** ``random``: return the images the draw WOULD hold out and write nothing. The validation dataset is not created either, so previewing costs nothing. */
  preview?: boolean;
  /** ``manual`` + ``add``: make the held-out set exactly ``image_ids``, dropping whatever else was in it. How an adjusted preview is committed as one choice rather than added to the last one. */
  replace?: boolean;
}

/**
 * The held-out set after the change, per side. For a ``preview`` these
describe the draw that WOULD be made; nothing has been written.
 */
export interface ClassifierHoldoutResponse {
  /** Held-out positive examples. */
  val_pos: number;
  /** Held-out negative examples. */
  val_neg: number;
  /** Images that joined the held-out set. */
  added: number;
  /** Images that left it. */
  removed: number;
  /** The images the held-out set now holds — or would, for a ``preview``. */
  image_ids: string[];
}

/**
 * Which images to label, and which side to put them on.
 */
export interface ClassifierLabel {
  image_ids: string[];
  /** The side to put these images on. ``none`` unlabels them: they leave both main example datasets and this classifier stops having an opinion on them.

* `positive` - positive
* `negative` - negative
* `none` - none */
  side: SideEnum;
}

/**
 * What a labelling call changed, per side.
 */
export interface ClassifierLabelResponse {
  /** Images that became examples on the requested side. */
  added: number;
  /** Images taken off the other side (or off both, for ``none``). */
  removed: number;
}

/**
 * Options for branching a version.
 */
export interface ClassifierNewVersion {
  /** Start the new version with a copy of this one's main example datasets. False gives it empty ones instead, for relabelling from scratch. */
  copy_examples?: boolean;
  /** Which of this version's additional positive datasets to carry over, by ``slug/version``. Omit to carry all of them; pass [] for none. Must be a subset of what this version has. */
  extra_pos_datasets?: string[];
  /** The negative side of ``extra_pos_datasets``. */
  extra_neg_datasets?: string[];
  /** What this new version is for: why it was branched, what is changing. Unlike ``description`` it belongs to the one version, and is not carried forward from the source. */
  version_note?: string;
}

export type ClassifierScoresScores = {[key: string]: number};

/**
 * A batch of scores to write onto image documents.
 */
export interface ClassifierScores {
  scores: ClassifierScoresScores;
  /** @nullable */
  run_id?: string | null;
}

/**
 * Options for starting a training run.
 */
export interface ClassifierTrain {
  /** Train even if a trained model already exists for the current example counts. Without it, an unchanged classifier returns its existing training instead of computing the same model again. */
  force?: boolean;
}

/**
 * @nullable
 */
export type ClassifierTrainingMetrics = {[key: string]: unknown} | null;

/**
 * A training run as the Training tab shows it. Everything is read-only:
rows are created by the train action and updated by the service's report.
 */
export interface ClassifierTraining {
  readonly id: string;
  readonly status: ClassifierTrainingStatusEnum;
  readonly dagster_run_id: string;
  /** @nullable */
  readonly dagster_run_url: string | null;
  readonly model_id: string;
  /** @nullable */
  readonly metrics: ClassifierTrainingMetrics;
  readonly error: string;
  readonly forced: boolean;
  readonly labels_version: string;
  readonly code_version: string;
  readonly n_pos: number;
  readonly n_neg: number;
  readonly n_val: number;
  readonly author: User;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * @nullable
 */
export type ClassifierTrainingReportMetrics = {[key: string]: unknown} | null;

/**
 * What the classifier service reports back onto a training record.
 */
export interface ClassifierTrainingReport {
  status: ClassifierTrainingReportStatusEnum;
  model_id?: string;
  /** @nullable */
  metrics?: ClassifierTrainingReportMetrics;
  error?: string;
}

/**
 * * `trained` - trained
* `failed` - failed
 */
export enum ClassifierTrainingReportStatusEnum {
  trained= 'trained',
  failed= 'failed',

}
/**
 * * `training` - Training
* `trained` - Trained
* `failed` - Failed
 */
export enum ClassifierTrainingStatusEnum {
  training= 'training',
  trained= 'trained',
  failed= 'failed',

}
export interface Count {
  count: number;
}

export interface Dataset {
  readonly slug_version: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  readonly version: number;
  /** @maxLength 100 */
  name: string;
  readonly type: string;
  readonly author: User;
  readonly group_count: number;
  description?: string;
  is_frozen?: boolean;
  readonly is_internal: boolean;
  /** @maxLength 255 */
  cover_image_id?: string;
  /** @nullable */
  readonly cover_thumbnail: string | null;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * POST .../images/ body: images to wrap in single_image groups and add.
 */
export interface DatasetAddImages {
  /**
   * @minItems 1
   * @maxItems 100
   */
  image_ids: string[];
}

/**
 * Request body for POST .../copy/. The new dataset inherits the source's type.
 */
export interface DatasetCopy {
  /** @maxLength 100 */
  name: string;
  /**
   * @maxLength 100
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug: string;
  description?: string;
}

export interface DatasetCreate {
  readonly slug_version: string;
  /**
   * @maxLength 100
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug: string;
  readonly version: number;
  /** @maxLength 100 */
  name: string;
  type: string;
  readonly author: User;
  readonly group_count: number;
  description?: string;
  is_frozen?: boolean;
  is_internal?: boolean;
  /** @maxLength 255 */
  cover_image_id?: string;
  /** @nullable */
  readonly cover_thumbnail: string | null;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * Response for GET .../groups/: one cursor page of active member groups.

No `group_count`: cursor pagination does not count, and the dataset already
carries the number (GET /datasets/<slug>/<version>/ annotates `group_count`).
 */
export interface DatasetGroups {
  /** @nullable */
  next: string | null;
  /** @nullable */
  previous: string | null;
  results: DatasetMember[];
}

/**
 * A member Group as it appears inside a Dataset listing.
 */
export interface DatasetMember {
  id: string;
  name: string;
  type: string;
  /** @nullable */
  readonly cover_thumbnail: string | null;
}

export interface DatasetUpdateGroups {
  /**
   * @minItems 1
   * @maxItems 100
   */
  group_ids: string[];
}

export interface DatasetUpdateGroupsResponse {
  updated_count: number;
}

/**
 * * `vits14` - vits14
* `vitb14` - vitb14
* `vitl14` - vitl14
* `vitg14` - vitg14
* `vits14_reg` - vits14_reg
* `vitb14_reg` - vitb14_reg
* `vitl14_reg` - vitl14_reg
* `vitg14_reg` - vitg14_reg
 */
export enum EmbeddingSpaceEnum {
  vits14= 'vits14',
  vitb14= 'vitb14',
  vitl14= 'vitl14',
  vitg14= 'vitg14',
  vits14_reg= 'vits14_reg',
  vitb14_reg= 'vitb14_reg',
  vitl14_reg= 'vitl14_reg',
  vitg14_reg= 'vitg14_reg',

}
/**
 * Shape of ``counts`` — declared so the generated clients get numbers
rather than an opaque object.
 */
export interface ExampleCounts {
  main_pos: number;
  main_neg: number;
  extra_pos: number;
  extra_neg: number;
  pos: number;
  neg: number;
  val_pos: number;
  val_neg: number;
  val_orphan: number;
}

/**
 * * `string` - String
* `number` - Number
* `integer` - Integer
* `object` - Object
* `array` - Array
* `boolean` - Boolean
* `null` - Null
 */
export enum FieldTypeEnum {
  string= 'string',
  number= 'number',
  integer= 'integer',
  object= 'object',
  array= 'array',
  boolean= 'boolean',
  null= 'null',

}
export type GroupMetadata = {[key: string]: unknown};

export interface Group {
  readonly id: string;
  /** @maxLength 255 */
  name: string;
  type: string;
  description?: string;
  /** @maxLength 255 */
  cover_image_id?: string;
  readonly cover_thumbnail: string;
  metadata?: GroupMetadata;
  readonly author: User;
  readonly image_count: number;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * POST /groups/bulk-delete/ body. Unknown or already-deleted ids are ignored, so the
cap is on what one request may carry, not on how many must exist.
 */
export interface GroupBulkDelete {
  /**
   * @minItems 1
   * @maxItems 1000
   */
  group_ids: string[];
}

export interface GroupBulkDeleteResponse {
  deleted_count: number;
}

export type GroupTypeMetadataSchema = {[key: string]: unknown};

export interface GroupType {
  /**
   * @maxLength 64
   * @pattern ^[a-z0-9_]+$
   */
  name: string;
  description?: string;
  metadata_schema?: GroupTypeMetadataSchema;
  roles?: GroupTypeRoleNested[];
  readonly group_count: number;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * Nested representation of a (role, is_required) pair on a GroupType.

The role must already exist in the Role table — create roles via
``POST /roles/`` before declaring a GroupType that references them.
 */
export interface GroupTypeRoleNested {
  role: string;
  is_required?: boolean;
}

export interface ImageIdsWithTagNames {
  /**
   * @minItems 1
   * @maxItems 1000
   */
  image_ids: string[];
  /**
   * @minItems 1
   * @maxItems 10
   */
  tag_names: string[];
}

export interface ImageLatentCreate {
  /**
   * @minLength 1
   * @maxLength 128
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  latent_type: string;
  file: string;
}

export interface LatentType {
  /**
   * @minLength 1
   * @maxLength 128
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  name: string;
  is_mask?: boolean;
  readonly image_count: number;
}

export type MembershipMetadata = {[key: string]: unknown};

/**
 * Read-only output shape for memberships. Writes go through the bulk PUT.
 */
export interface Membership {
  readonly id: string;
  /**
   * @minLength 1
   * @maxLength 512
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  image_id: string;
  /** @maxLength 64 */
  role: string;
  readonly metadata: MembershipMetadata;
  readonly date_created: string;
  readonly date_updated: string;
}

/**
 * * `random` - random
* `manual` - manual
 */
export enum ModeEnum {
  random= 'random',
  manual= 'manual',

}
export enum NullEnum {

}
/**
 * @nullable
 */
export type OSImageCocaEmbeddingProperty = OSImageCocaEmbedding | null;

export type OSImageAttributes = {[key: string]: unknown};

/**
 * @nullable
 */
export type OSImageRelatedImages = {[key: string]: string} | null;

export type OSImageClassifications = {[key: string]: number};

export interface OSImage {
  /**
   * @minLength 1
   * @maxLength 512
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  id: string;
  source?: string;
  image?: string;
  image_direct_url?: string;
  date_created?: string;
  date_updated?: string;
  author?: string;
  image_hash?: string;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  short_edge?: number | null;
  /** @nullable */
  pixel_count?: number | null;
  /** @nullable */
  aspect_ratio?: number | null;
  /** @nullable */
  aspect_ratio_fraction?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  thumbnail_direct_url?: string | null;
  /** @nullable */
  thumbnail_error?: boolean | null;
  /** @nullable */
  original_url?: string | null;
  tags?: string[];
  /** @nullable */
  coca_embedding?: OSImageCocaEmbeddingProperty;
  latents?: OSImageLatent[];
  attributes?: OSImageAttributes;
  /** @nullable */
  duplicate_state?: number | null;
  /** @nullable */
  related_images?: OSImageRelatedImages;
  /** @nullable */
  datasets?: string[] | null;
  memberships?: string[];
  classifications?: OSImageClassifications;
}

export interface OSImageCocaEmbedding {
  /** @nullable */
  vector?: number[] | null;
  /** @nullable */
  author?: string | null;
}

export type OSImageCreateAttributes = {[key: string]: unknown};

/**
 * @nullable
 */
export type OSImageCreateRelatedImages = {[key: string]: string} | null;

/**
 * ``datasets`` is derived from dataset membership, not writable on the image.

Without this, DRF would silently drop the key and answer 200, so a caller still
sending it would never learn its datasets were ignored.
 */
export interface OSImageCreate {
  /**
   * @minLength 1
   * @maxLength 512
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  id?: string;
  image?: string;
  image_url?: string;
  source: string;
  attributes?: OSImageCreateAttributes;
  tags?: string[];
  /** @nullable */
  related_images?: OSImageCreateRelatedImages;
}

export interface OSImageLatent {
  /**
   * @minLength 1
   * @maxLength 128
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  latent_type: string;
  file_direct_url?: string;
  is_mask?: boolean;
}

export interface OSImageSegmentation {
  captions: string[];
  segments: number[][];
}

export type OSImageUpdateAttributes = {[key: string]: unknown};

/**
 * @nullable
 */
export type OSImageUpdateRelatedImages = {[key: string]: string} | null;

/**
 * ``datasets`` is derived from dataset membership, not writable on the image.

Without this, DRF would silently drop the key and answer 200, so a caller still
sending it would never learn its datasets were ignored.
 */
export interface OSImageUpdate {
  source?: string;
  attributes?: OSImageUpdateAttributes;
  latents?: ImageLatentCreate[];
  tags?: string[];
  /** @pattern ^\[[\s\d,.\-\+eE]+\]$ */
  coca_embedding?: string;
  /** @nullable */
  related_images?: OSImageUpdateRelatedImages;
}

export interface PaginatedClassifierList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Classifier[];
}

export interface PaginatedDatasetList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Dataset[];
}

export interface PaginatedGroupList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Group[];
}

export interface PaginatedGroupTypeList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: GroupType[];
}

/**
 * Cursor page of a group's memberships (GET /groups/{id}/members/).
 */
export interface PaginatedMembership {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Membership[];
}

export interface PaginatedMembershipList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Membership[];
}

export interface PaginatedOSImage {
  /** @nullable */
  next: string | null;
  results: OSImage[];
}

export interface PaginatedQueryList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Query[];
}

export interface PaginatedRoleList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Role[];
}

export interface PaginatedTagList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Tag[];
}

export interface PaginatedTokenList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Token[];
}

// eslint-disable-next-line @typescript-eslint/no-redeclare
// @ts-ignore TS2450
export const PatchedClassifierEmbeddingSpace = {...EmbeddingSpaceEnum,...BlankEnum,} as const
export interface PatchedClassifier {
  readonly slug_version?: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug?: string;
  readonly version?: number;
  /** @maxLength 100 */
  name?: string;
  description?: string;
  version_note?: string;
  readonly author?: User;
  readonly main_pos_dataset?: string;
  readonly main_neg_dataset?: string;
  readonly val_dataset?: string;
  extra_pos_datasets?: string[];
  extra_neg_datasets?: string[];
  readonly counts?: ExampleCounts;
  readonly pos_count?: number;
  readonly neg_count?: number;
  embedding_space?: typeof PatchedClassifierEmbeddingSpace[keyof typeof PatchedClassifierEmbeddingSpace] ;
  is_frozen?: boolean;
  readonly date_created?: string;
  readonly date_updated?: string;
}

export interface PatchedDataset {
  readonly slug_version?: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug?: string;
  readonly version?: number;
  /** @maxLength 100 */
  name?: string;
  readonly type?: string;
  readonly author?: User;
  readonly group_count?: number;
  description?: string;
  is_frozen?: boolean;
  readonly is_internal?: boolean;
  /** @maxLength 255 */
  cover_image_id?: string;
  /** @nullable */
  readonly cover_thumbnail?: string | null;
  readonly date_created?: string;
  readonly date_updated?: string;
}

export type PatchedGroupMetadata = {[key: string]: unknown};

export interface PatchedGroup {
  readonly id?: string;
  /** @maxLength 255 */
  name?: string;
  type?: string;
  description?: string;
  /** @maxLength 255 */
  cover_image_id?: string;
  readonly cover_thumbnail?: string;
  metadata?: PatchedGroupMetadata;
  readonly author?: User;
  readonly image_count?: number;
  readonly date_created?: string;
  readonly date_updated?: string;
}

export type PatchedQueryCreateUpdateFilters = {[key: string]: unknown};

export interface PatchedQueryCreateUpdate {
  /**
   * @maxLength 100
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  /** @maxLength 100 */
  name?: string;
  description?: string;
  filters?: PatchedQueryCreateUpdateFilters;
}

export interface PatchedRole {
  /**
   * @maxLength 64
   * @pattern ^[a-z0-9_]+$
   */
  name?: string;
  description?: string;
  readonly group_types?: readonly string[];
  readonly group_count?: number;
}

export interface PatchedTag {
  readonly id?: string;
  /**
   * @minLength 1
   * @maxLength 300
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  name?: string;
  description?: string;
  readonly image_count?: number;
}

export interface PatchedToken {
  readonly id?: string;
  readonly key?: string;
  is_readonly?: boolean;
}

export type QueryFilters = {[key: string]: unknown};

export interface Query {
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  /** @maxLength 100 */
  name: string;
  description?: string;
  readonly author: User;
  readonly filters: QueryFilters;
}

export type QueryCreateUpdateFilters = {[key: string]: unknown};

export interface QueryCreateUpdate {
  /**
   * @maxLength 100
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug: string;
  /** @maxLength 100 */
  name: string;
  description?: string;
  filters?: QueryCreateUpdateFilters;
}

export interface Queue {
  total_images: StatsDict;
  images_missing_thumbnail: StatsDict;
  images_missing_coca_embedding: StatsDict;
  images_missing_duplicate_state: StatsDict;
  images_marked_as_duplicates: StatsDict;
  images_marked_for_deletion: StatsDict;
  images_with_disabled_latents: StatsDict;
}

/**
 * @nullable
 */
export type RelatedOSImageImage = OSImage | null;

export interface RelatedOSImage {
  name: string;
  image_id: string;
  /** @nullable */
  image?: RelatedOSImageImage;
}

export interface Role {
  /**
   * @maxLength 64
   * @pattern ^[a-z0-9_]+$
   */
  name: string;
  description?: string;
  readonly group_types: readonly string[];
  readonly group_count: number;
}

/**
 * * `positive` - positive
* `negative` - negative
* `none` - none
 */
export enum SideEnum {
  positive= 'positive',
  negative= 'negative',
  none= 'none',

}
/**
 * @nullable
 */
export type SimilarOSImageCocaEmbedding = OSImageCocaEmbedding | null;

export type SimilarOSImageAttributes = {[key: string]: unknown};

/**
 * @nullable
 */
export type SimilarOSImageRelatedImages = {[key: string]: string} | null;

export type SimilarOSImageClassifications = {[key: string]: number};

export interface SimilarOSImage {
  /**
   * @minLength 1
   * @maxLength 512
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  id: string;
  source?: string;
  image?: string;
  image_direct_url?: string;
  date_created?: string;
  date_updated?: string;
  author?: string;
  image_hash?: string;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  short_edge?: number | null;
  /** @nullable */
  pixel_count?: number | null;
  /** @nullable */
  aspect_ratio?: number | null;
  /** @nullable */
  aspect_ratio_fraction?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  thumbnail_direct_url?: string | null;
  /** @nullable */
  thumbnail_error?: boolean | null;
  /** @nullable */
  original_url?: string | null;
  tags?: string[];
  /** @nullable */
  coca_embedding?: SimilarOSImageCocaEmbedding;
  latents?: OSImageLatent[];
  attributes?: SimilarOSImageAttributes;
  /** @nullable */
  duplicate_state?: number | null;
  /** @nullable */
  related_images?: SimilarOSImageRelatedImages;
  /** @nullable */
  datasets?: string[] | null;
  memberships?: string[];
  classifications?: SimilarOSImageClassifications;
  similarity: number;
}

export interface SimilarToText {
  /**
   * @minLength 1
   * @maxLength 180
   */
  text: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  number: number;
}

export interface SimilarToVector {
  /** @pattern ^\[[\s\d,.\-\+eE]+\]$ */
  vector: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  number: number;
}

export interface StatsDict {
  current: number;
  date_updated: string;
  prev: number;
  prev_date_updated: string;
  change_per_second: number;
  time_left: number;
}

/**
 * * `date-time` - Date-time
* `time` - Time
* `date` - Date
* `duration` - Duration
* `email` - Email
* `hostname` - Hostname
* `ipv4` - IPv4
* `ipv6` - IPv6
* `uuid` - UUID
* `uri` - URI
 */
export enum StringFormatEnum {
  'date-time'= 'date-time',
  time= 'time',
  date= 'date',
  duration= 'duration',
  email= 'email',
  hostname= 'hostname',
  ipv4= 'ipv4',
  ipv6= 'ipv6',
  uuid= 'uuid',
  uri= 'uri',

}
export interface Tag {
  readonly id: string;
  /**
   * @minLength 1
   * @maxLength 300
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  name: string;
  description?: string;
  readonly image_count: number;
}

export interface TagImagesResponse {
  tags_created: number;
  images_tagged: number;
}

/**
 * * `dataset` - dataset
* `query` - query
* `source` - source
* `tag` - tag
* `all` - all
* `annotations` - annotations
 */
export enum TargetTypeEnum {
  dataset= 'dataset',
  query= 'query',
  source= 'source',
  tag= 'tag',

}
export interface Token {
  readonly id: string;
  readonly key: string;
  is_readonly?: boolean;
}

export interface Totals {
  images: StatsDict;
}

export interface User {
  readonly id: string;
  readonly email: string;
}

export type ClassifiersListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
embedding_space?: string;
is_frozen?: boolean;
name__prefix?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
slug?: string;
};

export type ClassifiersRunsListParams = {
embedding_space?: string;
is_frozen?: boolean;
name__prefix?: string;
/**
 * A search term.
 */
search?: string;
slug?: string;
};

export type ClassifiersTrainingsListParams = {
embedding_space?: string;
is_frozen?: boolean;
name__prefix?: string;
/**
 * A search term.
 */
search?: string;
slug?: string;
};

export type DatasetsListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
is_frozen?: boolean;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
slug?: string;
type?: string;
};

export type DatasetsGroupsRetrieveParams = {
/**
 * Opaque cursor from a previous page.
 */
cursor?: string;
/**
 * CSV of roles, presigned_url, thumbnail_url, os_metadata, datasets.
 */
include_fields?: string;
/**
 * Include group and membership metadata.
 */
include_metadata?: boolean;
/**
 * Member order by group creation date; default desc (newest first). asc starts at the earliest member — the cover group.
 */
order?: DatasetsGroupsRetrieveOrder;
/**
 * Groups per page, at most 2000.
 */
page_size?: number;
/**
 * CSV of roles to keep; default all.
 */
return_roles?: string;
};

export enum DatasetsGroupsRetrieveOrder {
  asc= 'asc',
  desc= 'desc',

}
export type GroupTypesListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
name__prefix?: string;
/**
 * Multiple values may be separated by commas.
 */
optional_roles?: string[];
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Multiple values may be separated by commas.
 */
required_roles?: string[];
/**
 * Multiple values may be separated by commas.
 */
roles?: string[];
};

export type GroupsListParams = {
author?: string;
/**
 * Resolve each group's cover_thumbnail as its earliest active member holding this role, instead of the explicit cover / first member. Groups without a member in this role get a null cover_thumbnail.
 */
cover_role?: string;
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Multiple values may be separated by commas.
 */
dataset?: string[];
/**
 * Multiple values may be separated by commas.
 */
has_role?: string[];
name__prefix?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Multiple values may be separated by commas.
 */
roles?: string[];
/**
 * A search term.
 */
search?: string;
/**
 * Multiple values may be separated by commas.
 */
type?: string[];
};

export type GroupsCreateParams = {
author?: string;
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Multiple values may be separated by commas.
 */
dataset?: string[];
/**
 * Multiple values may be separated by commas.
 */
has_role?: string[];
name__prefix?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Multiple values may be separated by commas.
 */
roles?: string[];
/**
 * A search term.
 */
search?: string;
/**
 * Multiple values may be separated by commas.
 */
type?: string[];
};

export type GroupsMembersListParams = {
/**
 * Opaque cursor from a previous page.
 */
cursor?: string;
/**
 * Memberships per page.
 */
page_size?: number;
};

export type GroupsBulkCreateParams = {
author?: string;
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Multiple values may be separated by commas.
 */
dataset?: string[];
/**
 * Multiple values may be separated by commas.
 */
has_role?: string[];
name__prefix?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Multiple values may be separated by commas.
 */
roles?: string[];
/**
 * A search term.
 */
search?: string;
/**
 * Multiple values may be separated by commas.
 */
type?: string[];
};

export type ImagesListParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * @minLength 1
 */
cursor?: string;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * The number of images to return per page.
 * @minimum 1
 * @maximum 2000
 */
page_size?: number;
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesRetrieveParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
};

export type ImagesRelatedListParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
};

export type ImagesSimilarListParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * @minimum 1
 * @maximum 100
 */
number?: number;
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesAggregateCreateParams = {
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesBucketCreateParams = {
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesCountRetrieveParams = {
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesFacetsRetrieveParams = {
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesFieldCatalogRetrieveParams = {
/**
 * Comma-separated list of discrete fields to fetch the complete value catalog for (e.g. source,tags,datasets). Ignores active filters and returns every distinct value.
 * @minLength 1
 */
fields: string;
};

export type ImagesRandomRetrieveParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Filter image_hash by a number of random prefixes. A higher num_prefixes will give you more samples, but slow down the query.
 * @minimum 1
 * @maximum 300
 */
num_prefixes?: number;
/**
 * The number of images to return per page.
 * @minimum 1
 * @maximum 2000
 */
page_size?: number;
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter image_hash by a number of random prefixes. A smaller prefix_length will give you more samples, but less random.
 * @minimum 1
 * @maximum 64
 */
prefix_length?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesSimilarToFileCreateParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
};

export type ImagesSimilarToFileCreateBody = {
  image: Blob;
  /** JSON string containing parameters like "number" */
  json?: string;
};

export type ImagesSimilarToTextCreateParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type ImagesSimilarToVectorCreateParams = {
/**
 * Return all available fields with ?all_fields=true
 */
all_fields?: boolean;
/**
 * Exact match for aspect_ratio.
 */
aspect_ratio?: number;
/**
 * aspect_ratio gt.
 */
aspect_ratio__gt?: number;
/**
 * aspect_ratio gte.
 */
aspect_ratio__gte?: number;
/**
 * aspect_ratio lt.
 */
aspect_ratio__lt?: number;
/**
 * aspect_ratio lte.
 */
aspect_ratio__lte?: number;
/**
 * aspect_ratio ne.
 */
aspect_ratio__ne?: number;
aspect_ratio_fraction?: string;
/**
 * Filter images with no aspect ratio fraction.
 */
aspect_ratio_fraction__empty?: boolean;
/**
 * Comma-separated list of attr:value pairs to filter by.
 */
attributes?: string[];
/**
 * Filter by classifier scores: comma-separated "<slug>/<version>__<op>:<score>" pairs, e.g. classifications=studio-shots/1__gte:0.8. Ops: gte, lte, gt, lt, eq (default eq).
 */
classifications?: string[];
/**
 * Filter images with no coca embedding.
 */
coca_embedding__empty?: boolean;
/**
 * Filter images that have any of these comma-separated list of datasets.
 */
datasets?: string[];
/**
 * Filter images that have all of these comma-separated list of datasets.
 */
datasets__all?: string[];
/**
 * Filter images with no datasets.
 */
datasets__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of datasets.
 */
datasets__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of datasets.
 */
datasets__ne_all?: string[];
/**
 * Filter images in any version of these comma-separated dataset slugs (version-agnostic).
 */
datasets__prefix?: string[];
/**
 * date_created gt.
 */
date_created__gt?: string;
/**
 * date_created gte.
 */
date_created__gte?: string;
/**
 * date_created lt.
 */
date_created__lt?: string;
/**
 * date_created lte.
 */
date_created__lte?: string;
/**
 * date_updated gt.
 */
date_updated__gt?: string;
/**
 * date_updated gte.
 */
date_updated__gte?: string;
/**
 * date_updated lt.
 */
date_updated__lt?: string;
/**
 * date_updated lte.
 */
date_updated__lte?: string;
duplicate_state?: string;
/**
 * Exclude fields that are there by default with ?exclude_fields=thumbnail
 * @minLength 1
 */
exclude_fields?: string;
/**
 * You can specify the exact fields with ?fields=id,image
 * @minLength 1
 */
fields?: string;
/**
 * Comma-separated list of group ids the image is a member of (any).
 */
group_ids?: string[];
/**
 * Filter to images in any group of this type (e.g. product, dataset, relationship).
 */
group_type?: string;
/**
 * Filter images that have all of these comma-separated list of attributes.
 */
has_attributes?: string[];
/**
 * Filter images scored by all of these comma-separated classifier slug/versions.
 */
has_classifications?: string[];
/**
 * Filter images that have all of these comma-separated list of latents.
 */
has_latents?: string[];
/**
 * Filter images that have all of these comma-separated list of latentmasks.
 */
has_masks?: string[];
/**
 * Exact match for height.
 */
height?: number;
/**
 * height gt.
 */
height__gt?: number;
/**
 * height gte.
 */
height__gte?: number;
/**
 * height lt.
 */
height__lt?: number;
/**
 * height lte.
 */
height__lte?: number;
/**
 * height ne.
 */
height__ne?: number;
/**
 * Comma-separated image ids. For showing a known set of images that is not a dataset, group or tag - a staged selection, for instance.
 */
ids?: string[];
/**
 * Include fields that are not there by default with ?include_fields=image,thumbnail
 * @minLength 1
 */
include_fields?: string;
/**
 * Filter images without any of these comma-separated list of attributes.
 */
lacks_attributes?: string[];
/**
 * Filter images not scored by any of these comma-separated classifier slug/versions.
 */
lacks_classifications?: string[];
/**
 * Filter images without any of these comma-separated list of latents.
 */
lacks_latents?: string[];
lacks_masks?: string[];
/**
 * Exact match for pixel_count.
 */
pixel_count?: number;
/**
 * pixel_count gt.
 */
pixel_count__gt?: number;
/**
 * pixel_count gte.
 */
pixel_count__gte?: number;
/**
 * pixel_count lt.
 */
pixel_count__lt?: number;
/**
 * pixel_count lte.
 */
pixel_count__lte?: number;
/**
 * pixel_count ne.
 */
pixel_count__ne?: number;
/**
 * Filter images by query.
 */
query?: string;
/**
 * Return specific latents only with ?return_latents=latent_type
 * @minLength 1
 */
return_latents?: string;
/**
 * Comma-separated list of membership roles (any group).
 */
roles?: string[];
/**
 * Filter images that have all of these comma-separated roles.
 */
roles__all?: string[];
/**
 * Filter images with no group memberships.
 */
roles__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated roles.
 */
roles__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated roles.
 */
roles__ne_all?: string[];
/**
 * Exact match for short_edge.
 */
short_edge?: number;
/**
 * short_edge gt.
 */
short_edge__gt?: number;
/**
 * short_edge gte.
 */
short_edge__gte?: number;
/**
 * short_edge lt.
 */
short_edge__lt?: number;
/**
 * short_edge lte.
 */
short_edge__lte?: number;
/**
 * short_edge ne.
 */
short_edge__ne?: number;
/**
 * Deprecated! Please use sources instead.
 */
source?: string;
/**
 * Filter images with no source.
 */
source__empty?: boolean;
/**
 * Comma-separated list of sources to filter by.
 */
sources?: string[];
/**
 * Comma-separated list of sources to exclude.
 */
sources__ne?: string[];
/**
 * Filter images that have any of these comma-separated list of tags.
 */
tags?: string[];
/**
 * Filter images that have all of these comma-separated list of tags.
 */
tags__all?: string[];
/**
 * Filter images with no tags.
 */
tags__empty?: boolean;
/**
 * Filter images that do not have any of these comma-separated list of tags.
 */
tags__ne?: string[];
/**
 * Filter images that do not have all of these comma-separated list of tags.
 */
tags__ne_all?: string[];
/**
 * Exact match for width.
 */
width?: number;
/**
 * width gt.
 */
width__gt?: number;
/**
 * width gte.
 */
width__gte?: number;
/**
 * width lt.
 */
width__lt?: number;
/**
 * width lte.
 */
width__lte?: number;
/**
 * width ne.
 */
width__ne?: number;
};

export type QueriesListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
};

export type QueriesCreateParams = {
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
};

export type QueriesRetrieveParams = {
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
};

export type QueriesUpdateParams = {
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
};

export type QueriesPartialUpdateParams = {
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
};

export type QueriesDestroyParams = {
/**
 * Only queries authored by the current user.
 */
mine?: boolean;
};

export type RolesListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
};

export type StatsAttributesListParams = {
/**
 * Search term
 */
search?: string;
};

export type StatsImageAspectRatioFractionsRetrieve200 = {[key: string]: number};

export type StatsImageSourcesRetrieveParams = {
/**
 * Search term
 */
search?: string;
};

export type StatsImageSourcesRetrieve200 = {[key: string]: number};

export type TagsListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
};

export type TokensListParams = {
/**
 * The pagination cursor value.
 */
cursor?: string;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

